import warnings

import matplotlib.pyplot as plt
import numpy as np
import requests

try:
    from open_ephys.control import OpenEphysHTTPServer
except ModuleNotFoundError:
    warnings.warn(
        "Could not import OpenEphysHTTPServer from module open_ephys. Will not be able to connect to OE GUI."
    )


class Npx2_Channel_Selector:
    """
    Class for automated channel selection for Neuropixels 2 probes, via the Open Ephys GUI.

    TODO: 
    - Support multiple probes

    Probe info:
    ------------
    The probe has 4 shanks, each with 2 columns of electrodes, spaced by 15/32 um in the y/x directions.
    Within each shank, there are ~3.33 banks of 384 electrodes.
    Within each bank, there are 8 channel "groups" of 48 electrodes, as shown in the Npx2 manual.
    These groups are always paired in the Npx2 manual, tho unclear if this matters. I refer to a horizontal group of 2 paired channels x 4 shanks as a "dense row".

    Usage info:
    -----------
    Currently implemented configurations:
    - linear_single_shank: Record from all 8 groups in a bank, on one particular shank.
    - dense_row: Record from a dense row across the probe (2 groups in each shank, in a given bank).
    - dense_row_offset: Record from a dense row across the probe, but offset by one group. (Alias for dense_row with offset=1)
    - diagonal: Record from a diagonal line across the probe (2 groups in each shank, in a given bank).
    - double_tall: Record from a single-width column of contacts across two adjacent banks, on a single shank.
    - half_bank: Record from a half-bank (4 groups) on two adjacent shanks (0 and 1, or 2 and 3).
    - half_bank_one_sided: Record from one side of a half-bank (4 groups) on all 4 shanks. (Inspired by Koun Onodera et al)
    - half_bank_checkerboard: Record from one side of a half-bank (4 groups) on all 4 shanks, in a checkerboard pattern. (Inspired by Koun Onodera et al)
    - half_bank_skipping: Record from one side of a half-bank (4 groups) on all 4 shanks, skipping every other row of channels. (Inspired by Koun Onodera et al)


    Implentation info:
    ------------------
    The class is designed to be used in conjunction with the Open Ephys GUI, which is used to select the channels.
    The object will automatically detect the Open Ephys GUI and connect to it, if it is open.

    The OE Neuropix-PXI processor numbers the electrodes on the shanks monotonically increasing, 
    starting from 1 at the bottom/left channel of shank 0, then 2 at the bottom/right channel, then 3/4, 5/6, etc.,
    all the way up to 1279 / 1280 at the top/right channel of shank 0, and then starting again at 1281 on the next shank.

    Internally, this class works by storing the current channel configuration as a list of electrode ids and shank numbers.
    The ids are zero-indexed internally and are converted to 1-indexed just before being sent to OE.
    Electrode positions (in x/y) are also stored, but these are purely cosmetic for display to the user.

    Different channel configurations are generated by selecting different combinations of electrodes with simple loop / slicing logic.
    The class does not know anything about the channel restrictions of the probe's electronics, so it is up to the user / developer
    to ensure that the selected channels are valid. If channels are sent to OE that are mapped to the same internal probe channel,
    whichever channel is enabled last will remain active.

    """

    def __init__(self):
        self.n_shanks = 4
        self.n_banks_per_shank = 3.33
        self.shank_pitch_x = 250  # um
        self.shank_width_x = 70  # um
        self.shank_offsets_x = np.array([0, 250, 500, 750])

        # Channel group info
        self.n_groups_per_bank = 8
        self.n_groups_per_row = 2  # this is a bit hacky, but since the groups are paired, we'll treat them each pair as a "row".
        self.n_rows_per_bank = self.n_groups_per_bank // self.n_groups_per_row
        # self.shank_1_order = [1, 3, 5, 7, 6, 8, 2, 4]
        # self.shank_2_order = [2, 4, 6, 8, 5, 7, 1, 3]
        # self.shank_3_order = [5, 7, 1, 3, 2, 4, 6, 8]
        # self.shank_4_order = [6, 8, 2, 4, 1, 3, 5, 7]
        self.n_ch_per_group = 48

        # Electrode info per shank
        self.n_cols = 2
        self.dy = 15
        self.dx = 32
        self.n_elec_per_shank = 1280
        self.n_elec_per_bank = 384
        self.shank_electrode_ids = np.arange(self.n_elec_per_shank)
        self.shank_electrode_positions = np.zeros((self.n_elec_per_shank, 2))
        for i in range(self.n_elec_per_shank):
            self.shank_electrode_positions[i, 0] = (i % 2) * self.dx
            self.shank_electrode_positions[i, 1] = (i // 2) * self.dy

        # State info
        self.current_eids = []
        self.current_shanks = []
        self.current_eposns = []

        # List of all current allowed configs
        self.allowed_configs = [
            "linear_single_shank",
            "dense_row",
            "dense_row_offset",
            "diagonal",
            "double_tall",
            "half_bank",
            "half_bank_one_sided",
            "half_bank_checkerboard",
            "half_bank_skipping",
        ]

    @staticmethod
    def query_oe_processors(port="37497"):
        r = requests.get(f"http://localhost:{port}/api/processors")
        return r.json()

    def query_npx_proc_info(self, id):
        info_str = self.gui.config(self.npx_pxi_processor_id, "NP INFO")["info"]
        info_str = info_str.replace("false", "False").replace("true", "True")
        info = eval(info_str)
        return info

    def oe_connect(self):

        try:
            # Get the processor id for the npx pxi
            self.oe_processors = self.query_oe_processors()["processors"]
        except (requests.exceptions.RequestException):
            print("hi")
            raise ConnectionError(
                "Could not connect to Open Ephys GUI. Make sure it is running."
            )
        
        # Find the processor id for the Neuropix-PXI
        for proc in self.oe_processors:
            if proc["name"] == "Neuropix-PXI":
                self.npx_pxi_processor_id = proc["id"]
                break

        # Connect to the OE GUI
        self.gui = OpenEphysHTTPServer()

        # Get info needed about the npx probe
        # TODO: allow multiple npx probes by storing info for each one
        npx_info = self.query_npx_proc_info(self.npx_pxi_processor_id)
        probe_info = npx_info["probes"][0]
        self.oe_info = dict(
            processor_id=self.npx_pxi_processor_id,
            basestation=probe_info["slot"],
            port=probe_info["port"],
            dock=probe_info["dock"],
        )

        # Try to send a basic command to validate
        cmd = "NP INFO"  
        self.gui.config(self.npx_pxi_processor_id, cmd)

        # Run for one second to ensure we're in business
        self.gui.acquire(1)

    def oe_select_current_channels(self, debug=False):
        """
        Select the current channels in the Open Ephys GUI.
        command is like: NP SELECT <bs> <port> <dock> <electrode> <electrode> <electrode> ...
        """
        if len(self.current_eids) == 0:
            raise ValueError("No electrodes selected.")

        # The pxi simply numbers the electrodes 1 2...1279 1280; 1281 1282...2559, 2560; etc.
        eids_pxi = [
            str(eid + sid * self.n_elec_per_shank + 1)  # Add 1 to make it 1-indexed
            for eid, sid in zip(self.current_eids, self.current_shanks)
        ]
        eids_pxi = " ".join(eids_pxi)
        d = self.oe_info
        cmd = f'NP SELECT {d["basestation"]} {d["port"]} {d["dock"]} {eids_pxi}'
        if debug:
            print(cmd)
        self.gui.config(d["processor_id"], cmd)

    def eids_from_group(self, bank, group):
        """
        Get the electrode ids for a given bank and group.
        """
        return np.arange(48) + 48 * group + 384 * bank

    def eposns_from_group(self, shank, bank, group):
        """
        Get the electrode positions for a given shank, bank and group.
        """
        electrode_ids = self.eids_from_group(bank, group)
        shank_electrode_posns = self.shank_electrode_positions[electrode_ids]
        return shank_electrode_posns + np.array([self.shank_offsets_x[shank], 0])

    def set_linear_single_shank(self, shank=0, bank=0):
        """
        Record from all 8 groups in a bank, on one particular shank.

        Parameters
        ----------
        shank : int
            The shank to record from. (0, 1, 2, or 3)

        bank : int
            The bank to record from. (0, 1, or 2)
        """
        self.current_eids = [
            self.eids_from_group(bank, g) for g in range(self.n_groups_per_bank)
        ]
        self.current_eids = np.concatenate(self.current_eids)
        self.current_shanks = [shank] * 384
        posns_within_shank = self.shank_electrode_positions[self.current_eids, :]
        shank_offsets = np.array([self.shank_offsets_x[shank], 0])
        self.current_eposns = posns_within_shank + shank_offsets

    def set_half_bank(self, shanks=[0, 1], bank=0, offset=0):
        """
        Record from a half-bank (4 groups) on two adjacent shanks (0 and 1, or 2 and 3).

        Parameters
        ----------
        shanks : list
            The shanks to record from. Must be [0, 1] or [2, 3].

        bank : int
            The bank to record from. (0, 1, or 2)

        offset : int
            The offset of the half-bank. 0 means lower 4 groups per shank,
            1 means upper 4 groups per shank.
        """
        self.current_eids = []
        self.current_shanks = []
        self.current_eposns = []
        assert len(shanks) == 2
        assert shanks == [0, 1] or shanks == [2, 3]
        assert offset == 0 or offset == 1
        for shank in shanks:
            for group in range(4):
                these_eids = self.eids_from_group(bank, group + 4 * offset)
                self.current_eids.append(these_eids)
                self.current_shanks.append([shank] * len(these_eids))
                posns_within_shank = self.shank_electrode_positions[these_eids, :]
                shank_offsets = np.array([self.shank_offsets_x[shank], 0])
                self.current_eposns.append(posns_within_shank + shank_offsets)

        self.current_eids = np.concatenate(self.current_eids)
        self.current_shanks = np.concatenate(self.current_shanks)
        self.current_eposns = np.concatenate(self.current_eposns, axis=0)

    def set_dense_row(self, bank=0, row_in_bank=0, offset=0):
        """
        Record from 2 groups in each shank, in a given bank.
        Each bank has 4 effective "rows" since the groups are paired.

        Parameters
        ----------
        bank : int
            The bank to record from. (0, 1, or 2)

        row_in_bank : int
            The row in the bank to record from. (0, 1, 2, or 3)

        offset : int
            The offset of the row. 1 offset unit moves the channels
            up by 1 group.
        """
        if row_in_bank >= self.n_rows_per_bank:
            raise ValueError(f"Invalid row_in_bank: {row_in_bank}")
        assert offset == 0 or offset == 1
        self.current_eids = []
        self.current_shanks = []
        self.current_eposns = []
        for shank in range(self.n_shanks):
            for i in range(2):
                group = row_in_bank * 2 + i + offset
                these_eids = self.eids_from_group(bank, group)
                self.current_eids.append(these_eids)
                self.current_shanks.append([shank] * len(these_eids))
                posns_within_shank = self.shank_electrode_positions[these_eids, :]
                shank_offsets = np.array([self.shank_offsets_x[shank], 0])
                self.current_eposns.append(posns_within_shank + shank_offsets)

        self.current_eids = np.concatenate(self.current_eids)
        self.current_shanks = np.concatenate(self.current_shanks)
        self.current_eposns = np.concatenate(self.current_eposns, axis=0)

    def set_diagonal(self, bank=0, lower_side="left"):
        """
        Record from 2 groups in each shank, in a given bank.
        There are two possible diagonals: left or right.

        Parameters
        ----------
        bank : int
            The bank to record from. (0, 1, or 2)

        lower_side : str
            The side of the probe to start the diagonal from. ("left" or "right")
        """
        # This can be done by taking groups indices 0 and 1 from shank 1,
        # 2 and 3 from shank 2, etc. The probe is designed such that this will always work.
        self.current_eids = []
        self.current_shanks = []
        self.current_eposns = []

        if lower_side == "left":
            shank_order = np.arange(self.n_shanks)
        elif lower_side == "right":
            shank_order = np.arange(self.n_shanks - 1, -1, -1)
        else:
            raise ValueError(f"Invalid lower_side: {lower_side}")

        for iShank, shank in enumerate(shank_order):
            groups_to_use = [2 * iShank, 2 * iShank + 1]
            for group in groups_to_use:
                these_eids = self.eids_from_group(bank, group)
                self.current_eids.append(these_eids)
                self.current_shanks.append([shank] * len(these_eids))
                posns_within_shank = self.shank_electrode_positions[these_eids, :]
                shank_offsets = np.array([self.shank_offsets_x[shank], 0])
                self.current_eposns.append(posns_within_shank + shank_offsets)

        self.current_eids = np.concatenate(self.current_eids)
        self.current_shanks = np.concatenate(self.current_shanks)
        self.current_eposns = np.concatenate(self.current_eposns, axis=0)

    def set_double_tall(self, shank=0, lower_bank=0, offset=0):
        """
        Record from a single-width column of contacts across two adjacent banks, on a single shank.

        Parameters
        ----------
        shank : int
            The shank to record from. (0, 1, 2, or 3)

        lower_bank : int
            The lower bank of the double-tall arrangement. (0, 1, or 2)

        offset : int
            The offset of the column. 1 offset unit moves the channels
            up by 1 group.
        """
        assert offset < 8
        self.current_eids = []
        self.current_shanks = []
        self.current_eposns = []

        banks_to_use = [lower_bank, lower_bank + 1]
        for iBank, bank in enumerate(banks_to_use):
            for group in range(self.n_groups_per_bank):
                these_eids = self.eids_from_group(bank, group + offset)
                if iBank == 0:
                    these_eids = these_eids[
                        ::2
                    ]  # Take every other electrode to get a single column
                elif iBank == 1:
                    these_eids = these_eids[1::2]
                self.current_eids.append(these_eids)
                self.current_shanks.append([shank] * len(these_eids))
                posns_within_shank = self.shank_electrode_positions[these_eids, :]
                shank_offsets = np.array([self.shank_offsets_x[shank], 0])
                self.current_eposns.append(posns_within_shank + shank_offsets)

        self.current_eids = np.concatenate(self.current_eids)
        self.current_shanks = np.concatenate(self.current_shanks)
        self.current_eposns = np.concatenate(self.current_eposns, axis=0)

    def set_half_bank_one_sided(self, bank=0, offset=0):
        """Record from one side of a half-bank (4 groups) on all 4 shanks.

        Parameters
        ----------
        bank : int
            The bank to record from. (0, 1, or 2)

        offset : int
            The offset of the half-bank. 1 offset unit moves the channels
            up by 2 groups.
        """
        assert offset < 4
        self.current_eids = []
        self.current_shanks = []
        self.current_eposns = []
        for shank in range(self.n_shanks):
            for group in range(4):
                these_eids = self.eids_from_group(bank, group + 2 * offset)

                # Depending on the offset, either shanks 0/2 and 1/3 will share channel groups (even offset), or
                # shanks 0/1 and 2/3 will share channel groups (odd offset).
                if offset % 2 == 0:
                    if (shank == 0) or (shank == 1):
                        start = 0
                    else:
                        start = 1  # ensure that shanks sharing channel groups use opposite set of channels
                elif offset % 2 == 1:
                    if (shank == 0) or (shank == 2):
                        start = 0
                    else:
                        start = 1
                these_eids = these_eids[
                    start::2
                ]  # Take every other electrode to get a single column
                self.current_eids.append(these_eids)
                self.current_shanks.append([shank] * len(these_eids))
                posns_within_shank = self.shank_electrode_positions[these_eids, :]
                shank_offsets = np.array([self.shank_offsets_x[shank], 0])
                self.current_eposns.append(posns_within_shank + shank_offsets)

        self.current_eids = np.concatenate(self.current_eids)
        self.current_shanks = np.concatenate(self.current_shanks)
        self.current_eposns = np.concatenate(self.current_eposns, axis=0)

    def set_half_bank_checkerboard(self, bank=0, offset=0):
        """Record from one side of a half-bank (4 groups) on all 4 shanks, in a checkerboard pattern.

        Parameters
        ----------
        bank : int
            The bank to record from. (0, 1, or 2)

        offset : int
            The offset of the half-bank. 1 offset unit moves the channels
            up by 2 groups.
        """
        assert offset < 4
        self.current_eids = []
        self.current_shanks = []
        self.current_eposns = []
        for shank in range(self.n_shanks):
            for group in range(4):
                these_eids = self.eids_from_group(bank, group + 2 * offset)
                # Depending on the offset, either shanks 0/2 and 1/3 will share channel groups (even offset), or
                # shanks 0/1 and 2/3 will share channel groups (odd offset).
                if offset % 2 == 0:
                    if (shank == 0) or (shank == 1):
                        # need to take channels 0, 3, 4, 7, 8, ...
                        _slice = np.concatenate(
                            [np.arange(0, 48, 4), np.arange(3, 48, 4)]
                        )
                    else:
                        _slice = np.concatenate(
                            [np.arange(1, 48, 4), np.arange(2, 48, 4)]
                        )
                elif offset % 2 == 1:
                    if (shank == 0) or (shank == 2):
                        _slice = np.concatenate(
                            [np.arange(0, 48, 4), np.arange(3, 48, 4)]
                        )
                    else:
                        _slice = np.concatenate(
                            [np.arange(1, 48, 4), np.arange(2, 48, 4)]
                        )

                these_eids = these_eids[_slice]
                self.current_eids.append(these_eids)
                self.current_shanks.append([shank] * len(these_eids))
                posns_within_shank = self.shank_electrode_positions[these_eids, :]
                shank_offsets = np.array([self.shank_offsets_x[shank], 0])
                self.current_eposns.append(posns_within_shank + shank_offsets)

        self.current_eids = np.concatenate(self.current_eids)
        self.current_shanks = np.concatenate(self.current_shanks)
        self.current_eposns = np.concatenate(self.current_eposns, axis=0)

    def set_half_bank_skipping(self, bank=0, offset=0):
        """Record from one side of a half-bank (4 groups) on all 4 shanks, skipping every other row of channels.

        Parameters
        ----------
        bank : int
            The bank to record from. (0, 1, or 2)

        offset : int
            The offset of the half-bank. 1 offset unit moves the channels
            up by 2 groups.
        """
        assert offset < 4
        self.current_eids = []
        self.current_shanks = []
        self.current_eposns = []
        for shank in range(self.n_shanks):
            for group in range(4):
                these_eids = self.eids_from_group(bank, group + 2 * offset)
                # Depending on the offset, either shanks 0/2 and 1/3 will share channel groups (even offset), or
                # shanks 0/1 and 2/3 will share channel groups (odd offset).
                if offset % 2 == 0:
                    if (shank == 0) or (shank == 3):
                        _slice = np.concatenate(
                            [np.arange(0, 48, 4), np.arange(1, 48, 4)]
                        )
                    else:
                        _slice = np.concatenate(
                            [np.arange(2, 48, 4), np.arange(3, 48, 4)]
                        )
                elif offset % 2 == 1:
                    if (shank == 1) or (shank == 2):
                        _slice = np.concatenate(
                            [np.arange(0, 48, 4), np.arange(1, 48, 4)]
                        )
                    else:
                        _slice = np.concatenate(
                            [np.arange(2, 48, 4), np.arange(3, 48, 4)]
                        )

                these_eids = these_eids[_slice]
                self.current_eids.append(these_eids)
                self.current_shanks.append([shank] * len(these_eids))
                posns_within_shank = self.shank_electrode_positions[these_eids, :]
                shank_offsets = np.array([self.shank_offsets_x[shank], 0])
                self.current_eposns.append(posns_within_shank + shank_offsets)

        self.current_eids = np.concatenate(self.current_eids)
        self.current_shanks = np.concatenate(self.current_shanks)
        self.current_eposns = np.concatenate(self.current_eposns, axis=0)

    def set_electrode_config(self, config, **kwargs):
        """
        Set the electrode configuration.

        Parameters
        ----------
        config : str
            The configuration to set. Must be one of the allowed_configs.

        kwargs : dict
            Additional keyword arguments to pass to the configuration function.
        """
        if config == "linear_single_shank":
            self.set_linear_single_shank(**kwargs)
        elif config == "dense_row":
            self.set_dense_row(**kwargs)
        elif config == "diagonal":
            self.set_diagonal(**kwargs)
        elif config == "double_tall":
            self.set_double_tall(**kwargs)
        elif config == "half_bank":
            self.set_half_bank(**kwargs)
        elif config == "dense_row_offset":
            self.set_dense_row(**kwargs, offset=1)
        elif config == "half_bank_one_sided":
            self.set_half_bank_one_sided(**kwargs)
        elif config == "half_bank_checkerboard":
            self.set_half_bank_checkerboard(**kwargs)
        elif config == "half_bank_skipping":
            self.set_half_bank_skipping(**kwargs)
        else:
            raise ValueError(f"Unknown configuration: {config}")

    def show_available_configs(self):
        """
        Print the available configurations.
        """
        for config in self.allowed_configs:
            fig, axs = plt.subplots(1, 2, figsize=(12, 4))
            self.set_electrode_config(config)
            self.plot(ax=axs[0])
            self.plot_zoomed(ax=axs[1])
            axs[0].set_title("Full probe")
            axs[1].set_title("Zoomed view")
            plt.suptitle(config)

    def plot(self, ax=None):
        """
        Plot the current electrode configuration.
        """
        if ax is None:
            fig, ax = plt.subplots(figsize=(3, 2))

        # Draw the shanks as rectangles of height 1280 * self.dy, and width self.shank_pitch_x
        offset = self.shank_width_x // 4
        max_y = self.shank_electrode_positions[-1, 1] + self.dy
        min_y = -200
        for shank in range(4):
            x = self.shank_offsets_x[shank] - offset
            ax.plot([x, x], [min_y, max_y], "k")
            ax.plot(
                [x + self.shank_width_x, x + self.shank_width_x], [min_y, max_y], "k"
            )
            ax.plot([x, x + self.shank_width_x], [min_y, min_y], "k")
            ax.plot([x, x + self.shank_width_x], [max_y, max_y], "k")

        # Draw the currently selected electrodes
        ax.scatter(self.current_eposns[:, 0], self.current_eposns[:, 1], s=2)
        ax.set_ylabel("Y (um)")
        ax.set_xlabel("X (um)")
        return ax

    def plot_zoomed(self, ax=None):

        if ax is None:
            fig, ax = plt.subplots(figsize=(6, 4))

        # Draw the shanks as rectangles of height 1280 * self.dy, and width self.shank_pitch_x
        offset = self.shank_width_x // 4
        max_y = self.shank_electrode_positions[-1, 1] + self.dy
        min_y = -20
        for shank in range(4):
            x = self.shank_offsets_x[shank] - offset
            ax.plot([x, x], [min_y, max_y], "k")
            ax.plot(
                [x + self.shank_width_x, x + self.shank_width_x], [min_y, max_y], "k"
            )
            ax.plot([x, x + self.shank_width_x], [min_y, min_y], "k")
            ax.plot([x, x + self.shank_width_x], [max_y, max_y], "k")

        # Draw the currently selected electrodes
        ax.scatter(self.current_eposns[:, 0], self.current_eposns[:, 1], s=30, c="gold")
        min_y_elecs = np.min(self.current_eposns[:, 1])

        # Draw all possible electrode positions as open black circles
        for shank in range(4):
            i = np.array(list(range(self.n_elec_per_shank)))
            x = self.shank_electrode_positions[i, 0] + self.shank_offsets_x[shank]
            y = self.shank_electrode_positions[i, 1]
            ax.scatter(x, y, s=30, edgecolor="k", facecolor="none", linewidth=0.5)

        ax.set_ylabel("Y (um)")
        ax.set_xlabel("X (um)")
        # ax.set_xlim([-50, 400])
        ax.set_ylim([min_y_elecs - 50, min_y_elecs + 200])
        return ax




class Npx1_Channel_Selector:
    """
    Channel selector for Neuropixels 1.0 (single shank) via the Open Ephys GUI.

    Capabilities
    ------------
    - oe_connect(): connect to OE GUI, find Neuropix-PXI, cache bs/port/dock
    - select_bank(bank): select bank 'A'/'B'/'C'
    - select_electrodes(eids_1based): select explicit 1-based electrode indices (1..960)
    - sweep_all_banks(record_s=60, order=('A','B','C')): record each bank sequentially

    Notes
    -----
    - NP1.0 has 960 selectable sites; 384 can be active at once.
    - Bank A: 0..383; Bank B: 384..767; Bank C: 768..959 plus backfill 576..767 (to reach 384).
      (We keep 0-based internally and convert to 1-based only when sending to OE.)
    - For NP1.0, dock is always 1 in the NP SELECT command.
    """

    def __init__(self):
        # Probe constants
        self.n_shanks = 1
        self.n_elec_total = 960
        self.n_elec_per_bank = 384

        # Cosmetic layout (optional; in case you later plot selections)
        self.dx = 16   # μm
        self.dy = 20   # μm
        self.n_cols = 4
        self.electrode_xy = np.zeros((self.n_elec_total, 2), dtype=float)
        for i in range(self.n_elec_total):
            col = i % self.n_cols
            row = i // self.n_cols
            self.electrode_xy[i] = [col * self.dx, row * self.dy]

        # OE handles
        self.gui = None
        self.npx_pxi_processor_id = None
        self.oe_info = None  # dict with processor_id, basestation, port, dock

        # Cache of current selection (0-based)
        self.current_eids0 = np.array([], dtype=int)

    # ---------- Open Ephys interaction ----------
    @staticmethod
    def query_oe_processors(port="37497"):
        r = requests.get(f"http://localhost:{port}/api/processors")
        r.raise_for_status()
        return r.json()

    def _query_np_info(self):
        info_str = self.gui.config(self.npx_pxi_processor_id, "NP INFO")["info"]
        info_str = info_str.replace("false", "False").replace("true", "True")
        return eval(info_str)

    def oe_connect(self):
        """Connect to OE, locate Neuropix-PXI, and cache basestation/port/dock for the first probe."""
        try:
            procs = self.query_oe_processors()["processors"]
        except requests.exceptions.RequestException as e:
            raise ConnectionError("Could not connect to Open Ephys GUI at localhost:37497.") from e

        for p in procs:
            if p["name"] == "Neuropix-PXI":
                self.npx_pxi_processor_id = p["id"]
                break
        if self.npx_pxi_processor_id is None:
            raise RuntimeError("Neuropix-PXI processor not found in OE GUI.")

        # Initialize OE HTTP client and probe info
        self.gui = OpenEphysHTTPServer()

        npx_info = self._query_np_info()
        probe0 = npx_info["probes"][0]  # use first detected probe by default
        # NP1.0 always uses dock=1 in NP SELECT
        self.oe_info = dict(
            processor_id=self.npx_pxi_processor_id,
            basestation=probe0["slot"],   # bs
            port=probe0["port"],          # port
            dock=1,                       # NP1.0
        )

        # Sanity ping + short acquire
        self.gui.config(self.npx_pxi_processor_id, "NP INFO")
        self.gui.acquire(1)

    # ---------- Bank definitions (0-based internally) ----------
    @property
    def bank_A_eids0(self):
        return np.arange(0, 384, dtype=int)

    @property
    def bank_B_eids0(self):
        return np.arange(384, 768, dtype=int)

    @property
    def bank_C_eids0(self):
        head = np.arange(768, 960, dtype=int)   # 192
        tail = np.arange(576, 768, dtype=int)   # +192 = 384
        return np.concatenate([head, tail])

    def get_bank(self, bank: str):
        bank = bank.upper()
        if bank == "A":
            return self.bank_A_eids0
        if bank == "B":
            return self.bank_B_eids0
        if bank == "C":
            return self.bank_C_eids0
        raise ValueError("bank must be 'A', 'B', or 'C'")

    # ---------- Selection helpers ----------
    def _send_np_select(self, eids0, debug=False):
        if self.gui is None or self.oe_info is None:
            raise RuntimeError("Not connected to OE. Call oe_connect() first.")
        eids1 = (np.asarray(eids0, dtype=int) + 1).astype(str)  # 1-based for OE
        eid_str = " ".join(eids1.tolist())
        d = self.oe_info
        cmd = f'NP SELECT {d["basestation"]} {d["port"]} {d["dock"]} {eid_str}'
        if debug:
            print(cmd)
        self.gui.config(d["processor_id"], cmd)
        self.current_eids0 = np.asarray(eids0, dtype=int)

    def select_bank(self, bank: str, debug=False):
        """Select a single bank ('A','B','C')."""
        self._send_np_select(self.get_bank(bank), debug=debug)

    def select_electrodes(self, eids_1based, debug=False):
        """Select explicit 1-based electrodes (1..960)."""
        e0 = np.asarray(eids_1based, dtype=int) - 1
        if np.any(e0 < 0) or np.any(e0 >= self.n_elec_total):
            raise ValueError("Electrode indices out of range for NP1.0 (1..960).")
        self._send_np_select(e0, debug=debug)

    def sweep_all_banks(self, record_s=60, order=("A", "B", "C"), debug=False):
        """Record each bank for record_s seconds (requires OE signal chain ready to record)."""
        if self.gui is None:
            raise RuntimeError("Call oe_connect() first.")
        for b in order:
            self.select_bank(b, debug=debug)
            self.gui.record(record_s)

    # ---------- Optional conveniences ----------
    def get_current_electrodes_1based(self):
        return (self.current_eids0 + 1).tolist()

    def get_current_xy(self):
        if self.current_eids0.size == 0:
            return np.empty((0, 2))
        return self.electrode_xy[self.current_eids0]


def make_npx_selector_from_gui(prefer='auto'):
    """
    Utility: connect to OE and return the appropriate selector instance.

    prefer:
        'auto'  -> inspect NP INFO (# of shanks) to decide NP1 vs NP2
        'np1'   -> force Npx1_Channel_Selector
        'np2'   -> force Npx2_Channel_Selector
    """
    if prefer == 'np1':
        sel = Npx1_Channel_Selector()
        sel.oe_connect()
        return sel
    if prefer == 'np2':
        sel = Npx2_Channel_Selector()
        sel.oe_connect()
        return sel

    # auto-detect
    # We reuse NP2's HTTP code path because it already exists in this file.
    try:
        # Instantiate a lightweight OE client to read NP INFO
        _gui = OpenEphysHTTPServer()
        # Find NP-PXI
        procs = requests.get("http://localhost:37497/api/processors").json()["processors"]
        npx_id = None
        for p in procs:
            if p["name"] == "Neuropix-PXI":
                npx_id = p["id"]
                break
        if npx_id is None:
            raise RuntimeError("Neuropix-PXI processor not found.")
        info_str = _gui.config(npx_id, "NP INFO")["info"].replace("false","False").replace("true","True")
        info = eval(info_str)
        probe0 = info["probes"][0]
        # Heuristic: NP2 has 4 shanks; NP1 has 1
        n_shanks = probe0.get("n_shanks") or probe0.get("num_shanks") or None
    except Exception:
        n_shanks = None

    if n_shanks == 1:
        sel = Npx1_Channel_Selector()
    else:
        sel = Npx2_Channel_Selector()
    sel.oe_connect()
    return sel
# --- END ADDITION ------------------------------------------------------------





